{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xcell
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.12"

source:
  fn: xcell_1.12.tar.gz
  url:
    - https://github.com/dviraran/xCell/archive/1.12.tar.gz
  sha256: d204f4069708263b80920aa11e1a5815d9584c9e49237de7f40931856bec4cdf

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-base =3.5.1
    - r-roxygen2 =6.1.1
    - r-mass =7.3_51.4
    - bioconductor-gsva =1.30.0
    - bioconductor-gseabase =1.44.0
    - r-pracma =2.2.5
    - posix               # [win]
    - {{native}}toolchain # [win]
      #    - gcc                 # [not win]

  run:
    - r-base >=3.1.0
    - r-roxygen2 >=6.0.1
    - r-mass >=7.3_48
    - bioconductor-gsva >=1.26.0
    - bioconductor-gseabase >=1.40.0
    - r-pracma >=2.0.4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xCell')" # [not win]
    - "\"%R%\" -e \"library('xCell')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/dviraran/xCell
  license: GPL-3
  summary: "Tissues are a complex milieu consisting of numerous cell types. In cancer, understanding the cellular heterogeneity in the tumor microenvironment is an emerging field of research. Numerous methods have been published in recent years for the enumeration of cell subsets from tissue expression profiles. However, the available methods suffer from three major problems: inferring cell subset based on gene sets learned and verified from limited sources; displaying only partial portrayal of the full cellular heterogeneity; and insufficient validation in mixed tissues. The xCell package performs cell type enrichment analysis from gene expression data for 64 immune and stroma cell types. xCell is a gene signatures-based method learned from thousands of pure cell types from various sources. xCell applies a novel technique for reducing associations between closley related cell types. xCell signatures were validated using extensive in-silico simulations and also cytometry immunophenotyping, and were shown to outperform previous methods. xCell allows researchers to reliably portray the cellular heterogeneity landscape of tissue expression profiles."
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: xCell
# Type: Package
# Title: Cell type enrichment analysis
# Version: 1.1.0
# Author: person("Dvir", "Aran", email = "dvir.aran@ucsf.edu",role = c("aut", "cre"))
# Maintainer: Dvir Aran <dvir.aran@ucsf.edu>
# Description: Tissues are a complex milieu consisting of numerous cell types.
#     In cancer, understanding the cellular heterogeneity in the tumor microenvironment is
#     an emerging field of research. Numerous methods have been published in recent years
#     for the enumeration of cell subsets from tissue expression profiles. However, the
#     available methods suffer from three major problems: inferring cell subset based on
#     gene sets learned and verified from limited sources; displaying only partial portrayal
#     of the full cellular heterogeneity; and insufficient validation in mixed tissues.
#     The xCell package performs cell type enrichment analysis from gene expression data for
#     64 immune and stroma cell types. xCell is a gene signatures-based method learned from
#     thousands of pure cell types from various sources. xCell applies a novel technique for
#     reducing associations between closley related cell types. xCell signatures were
#     validated using extensive in-silico simulations and also cytometry immunophenotyping,
#     and were shown to outperform previous methods. xCell allows researchers to reliably
#     portray the cellular heterogeneity landscape of tissue expression profiles.
# License: GPL-3
# Encoding: UTF-8
# URL: http://xCell.ucsf.edu
# LazyData: true
# Depends: R (>= 3.1.0)
# Imports:
#    GSVA,
#    GSEABase,
#    pracma,
#    utils,
#    stats,
#    MASS
# RoxygenNote: 6.0.1
# Suggests: knitr,
#     rmarkdown,
#     testthat
# VignetteBuilder: knitr
